import type { paths, components } from "./api"; // generated by openapi-typescript
import createClient, { Middleware } from "openapi-fetch";

export type listEnvironmentsOptions =
  paths["/apiKey/v2/test-targets/{testTargetId}/environments"]["get"]["parameters"]["path"];
export type executeTestsBody =
  components["schemas"]["TestTargetExecutionRequest"];
export type getTestReportParams =
  paths["/apiKey/v2/test-targets/{testTargetId}/test-reports/{testReportId}"]["get"]["parameters"]["path"];
export type TestReport = components["schemas"]["TestReport"];
export type SuccessResponse = components["schemas"]["SuccessResponse"];
export type PrivateLocationInfo = components["schemas"]["PrivateLocationInfo"];
export type PostEnvironmentOptions =
  paths["/apiKey/v2/test-targets/{testTargetId}/environments"]["post"]["requestBody"]["content"]["application/json"] & {
    testTargetId: string;
  };

export type UpdateEnvironmentOptions =
  paths["/apiKey/v2/test-targets/{testTargetId}/environments/{environmentId}"]["patch"]["requestBody"]["content"]["application/json"];
export type EnvironmentResponse = components["schemas"]["EnvironmentResponse"];

export type ErrorResponse = components["schemas"]["ZodResponse"] | undefined;

const BASE_URL = "https://app.octomind.dev/api";

const client = createClient<paths>({ baseUrl: BASE_URL });

const authMiddleware: Middleware = {
  async onRequest({ request }) {
    const apiKey = process.env.APIKEY;
    if (!apiKey) {
      throw new Error("APIKEY environment variable is not set");
    }
    request.headers.set("x-api-key", apiKey);
    return request;
  },
};
client.use(authMiddleware);

const handleError = (error: ErrorResponse) => {
  if (error) {
    console.error(error);
    process.exit(1);
  }
};

export const listEnvironments = async (
  options: listEnvironmentsOptions & { json?: boolean },
): Promise<void> => {
  const { data, error } = await client.GET(
    "/apiKey/v2/test-targets/{testTargetId}/environments",
    {
      params: {
        path: { testTargetId: options.testTargetId },
      },
    },
  );

  handleError(error);

  if (options.json) {
    outputResult(data);
    return;
  }

  console.log("Environments:");
  if (data) {
    data.forEach((environment) => {
      console.log(`- Name: ${environment.name}`);
      console.log(`  ID: ${environment.id}`);
      console.log(`  Discovery URL: ${environment.discoveryUrl}`);
      console.log(`  Updated At: ${environment.updatedAt}`);
    });
  }
};

const outputResult = (result: unknown): void => {
  console.log(JSON.stringify(result, null, 2));
};

export const executeTests = async (
  options: executeTestsBody & { json?: boolean; description?: string },
): Promise<void> => {
  const { data, error } = await client.POST("/apiKey/v2/execute", {
    body: {
      testTargetId: options.testTargetId,
      url: options.url,
      context: {
        source: "manual",
        description: options.description || "CLI execution",
        triggeredBy: {
          type: "USER",
          userId: "cli-user",
        },
      },
      environmentName: options.environmentName,
      tags: options.tags,
      variablesToOverwrite: options.variablesToOverwrite,
    },
  });

  handleError(error);

  if (options.json) {
    outputResult(data);
    return;
  }

  if (data) {
    console.log("Test execution started successfully!");
    console.log("Test Report URL:", data.testReportUrl);
    console.log("Report Status:", data.testReport?.status);

    if (data.testReport?.testResults?.length ?? 0 > 0) {
      console.log("\nTest Results:");
      data.testReport?.testResults?.forEach((result) => {
        console.log(`- Test ${result.testCaseId}: ${result.status}`);
        if (result.errorMessage) {
          console.log(`  Error: ${result.errorMessage}`);
        }
        if (result.traceUrl) {
          console.log(`  Trace: ${result.traceUrl}`);
        }
      });
    }
  }
};

export const getTestReport = async (
  options: getTestReportParams & { json?: boolean },
): Promise<void> => {
  const { data, error } = await client.GET(
    "/apiKey/v2/test-targets/{testTargetId}/test-reports/{testReportId}",
    {
      params: {
        path: {
          testTargetId: options.testTargetId,
          testReportId: options.testReportId,
        },
      },
    },
  );

  handleError(error);

  if (options.json) {
    outputResult(data);
    return;
  }

  const response = data as TestReport;
  console.log("Test Report Details:");
  console.log("Status:", response.status);
  console.log("Execution URL:", response.executionUrl);

  if ((response.testResults ?? []).length > 0) {
    console.log("\nTest Results:");
    (response.testResults ?? []).forEach((result) => {
      console.log(`- Test ${result.testCaseId}: ${result.status}`);
      if (result.errorMessage) {
        console.log(`  Error: ${result.errorMessage}`);
      }
      if (result.traceUrl) {
        console.log(`  Trace: ${result.traceUrl}`);
      }
    });
  }
};

export const registerLocation = async (options: {
  address: string;
  name: string;
  username: string;
  password: string;
  json?: boolean;
}): Promise<void> => {
  const { data, error } = await client.PUT(
    "/apiKey/v1/private-location/register",
    {
      body: {
        name: options.name,
        registrationData: {
          address: options.address,
          username: options.username,
          password: options.password,
        },
      },
    },
  );

  handleError(error);

  const response = data as SuccessResponse;

  if (options.json) {
    outputResult(response);
    return;
  }

  console.log("Registration result:", response.success ? "Success" : "Failed");
};

export const unregisterLocation = async (options: {
  name: string;
  json?: boolean;
}): Promise<void> => {
  const { data, error } = await client.PUT(
    "/apiKey/v1/private-location/unregister",
    {
      body: {
        name: options.name,
      },
    },
  );

  handleError(error);
  const response = data as SuccessResponse;

  if (options.json) {
    outputResult(response);
    return;
  }

  console.log(
    "Unregistration result:",
    response.success ? "Success" : "Failed",
  );
};

export const listPrivateLocations = async (options: {
  json?: boolean;
}): Promise<void> => {
  const { data, error } = await client.GET("/apiKey/v1/private-location");

  handleError(error);

  const response = data as PrivateLocationInfo;
  if (options.json) {
    outputResult(response);
    return;
  }

  console.log("Private Locations:");
  response.forEach((location) => {
    console.log(`- Name: ${location.name}`);
    console.log(`  Status: ${location.status}`);
    console.log(`  Address: ${location.address}`);
  });
};

export const createEnvironment = async (
  options: PostEnvironmentOptions & {
    json?: boolean;
    testAccountUsername?: string;
    testAccountPassword?: string;
    basicAuthUsername?: string;
    basicAuthPassword?: string;
    privateLocationName?: string;
    testAccountOtpInitializerKey?: string;
  },
): Promise<void> => {
  const { data, error } = await client.POST(
    "/apiKey/v2/test-targets/{testTargetId}/environments",
    {
      params: {
        path: { testTargetId: options.testTargetId },
      },
      body: {
        name: options.name,
        discoveryUrl: options.discoveryUrl,
        testAccount: {
          username: options.testAccountUsername,
          password: options.testAccountPassword,
        },
        basicAuth: {
          username: options.basicAuthUsername,
          password: options.basicAuthPassword,
        },
        testAccountOtpInitializerKey: options.testAccountOtpInitializerKey,
        privateLocationName: options.privateLocationName,
        additionalHeaderFields: options.additionalHeaderFields,
      },
    },
  );

  handleError(error);

  const response = data as EnvironmentResponse;

  if (options.json) {
    outputResult(response);
    return;
  }

  console.log("Environment created successfully!");
  console.log(`- Name: ${response.name}`);
  console.log(`  ID: ${response.id}`);
  console.log(`  Discovery URL: ${response.discoveryUrl}`);
  console.log(`  Updated At: ${response.updatedAt}`);
};

export const updateEnvironment = async (
  options: UpdateEnvironmentOptions & {
    testTargetId: string;
    environmentId: string;
    json?: boolean;
    testAccountUsername?: string;
    testAccountPassword?: string;
    basicAuthUsername?: string;
    basicAuthPassword?: string;
    privateLocationName?: string;
    testAccountOtpInitializerKey?: string;
  },
): Promise<void> => {
  const { data, error } = await client.PATCH(
    "/apiKey/v2/test-targets/{testTargetId}/environments/{environmentId}",
    {
      params: {
        path: {
          testTargetId: options.testTargetId,
          environmentId: options.environmentId,
        },
      },
      body: {
        name: options.name,
        discoveryUrl: options.discoveryUrl,
        testAccount: {
          username: options.testAccountUsername,
          password: options.testAccountPassword,
        },
        otpInitializerKey: options.testAccountOtpInitializerKey,
        basicAuth: {
          username: options.basicAuthUsername,
          password: options.basicAuthPassword,
        },
        privateLocationName: options.privateLocationName,
      },
    },
  );

  handleError(error);

  const response = data as EnvironmentResponse;

  if (options.json) {
    outputResult(response);
    return;
  }

  console.log("Environment updated successfully!");
  console.log(`- Name: ${response.name}`);
  console.log(`  ID: ${response.id}`);
  console.log(`  Discovery URL: ${response.discoveryUrl}`);
  console.log(`  Updated At: ${response.updatedAt}`);
};

export const deleteEnvironment = async (options: {
  testTargetId: string;
  environmentId: string;
  json?: boolean;
}): Promise<void> => {
  const { error } = await client.DELETE(
    "/apiKey/v2/test-targets/{testTargetId}/environments/{environmentId}",
    {
      params: {
        path: {
          testTargetId: options.testTargetId,
          environmentId: options.environmentId,
        },
      },
    },
  );

  handleError(error);

  if (options.json) {
    outputResult({ success: true });
    return;
  }

  console.log("Environment deleted successfully!");
};
