import createClient, { Client, Middleware } from "openapi-fetch";

import type { components, paths } from "../api"; // generated by openapi-typescript
import { loadConfig } from "../config";
import { version } from "../version";

export const BASE_URL =
  process.env.OCTOMIND_API_URL || "https://app.octomind.dev/api";
type ErrorResponse =
  | components["schemas"]["ZodResponse"]
  | string
  | { status: "error"; error: string }
  | { status: "has dependencies"; dependencyIds: string[] }
  | undefined;

const client: Client<paths> = createClient<paths>({ baseUrl: BASE_URL });

export const createClientFromUrlAndApiKey = ({
  baseUrl,
  apiKey,
}: {
  baseUrl: string;
  apiKey: string;
}): Client<paths> => {
  const customClient = createClient<paths>({ baseUrl });
  customClient.use(
    createAuthMiddleware({
      getApiKey: () => ({
        apiKey,
      }),
    }),
  );
  return customClient;
};

const createAuthMiddleware = ({
  getApiKey,
}: {
  getApiKey: () =>
    | Promise<{ apiKey?: string | undefined }>
    | { apiKey: string };
}): Middleware => {
  return {
    async onRequest({ request }) {
      const { apiKey } = await getApiKey();
      if (!apiKey) {
        throw new Error(
          "API key is required. Please configure it first by running 'octomind init'",
        );
      }
      request.headers.set("x-api-key", apiKey);
      request.headers.set("user-agent", `octomind-cli/${version}`);
      return request;
    },
    async onResponse({ response }) {
      const { body, ...resOptions } = response;
      if (!response.ok) {
        const res = new Response(body, resOptions);
        const errorBody = await res.text();
        return new Response(
          `${response.status}, ${response.statusText}: ${errorBody ? errorBody : ""}`,
          { ...resOptions, status: response.status },
        );
      }
      return response;
    },
    onError({ error }) {
      console.error(error);
      process.exit(1);
    },
  };
};

client.use(createAuthMiddleware({ getApiKey: loadConfig }));

export { client, paths };

export const handleError = (error: ErrorResponse) => {
  if (error) {
    console.error(error);
    if (typeof error === "string" && error.startsWith("403")) {
      console.error(
        "You are not authorized. Check your API key or do a 'octomind init' to set it up.",
      );
    }
    process.exit(1);
  }
};

export type ListOptions = {
  json?: boolean;
};
export const logJson = (result: unknown): void => {
  console.log(JSON.stringify(result, null, 2));
};
