import type { components, paths } from "../api"; // generated by openapi-typescript
import { logger } from "../logger";
import { client, handleError, ListOptions, logJson } from "./client";

export type GetEnvironmentsOptions =
  paths["/apiKey/v3/test-targets/{testTargetId}/environments"]["get"]["parameters"]["path"];
export type PostEnvironmentOptions =
  paths["/apiKey/v3/test-targets/{testTargetId}/environments"]["post"]["requestBody"]["content"]["application/json"] & {
    testTargetId: string;
  };
export type UpdateEnvironmentOptions =
  paths["/apiKey/v3/test-targets/{testTargetId}/environments/{environmentId}"]["patch"]["requestBody"]["content"]["application/json"];
export type EnvironmentResponse = components["schemas"]["EnvironmentResponse"];

export type GetEnvironmentOptions = {
  testTargetId: string;
  environmentId: string;
};

export const listEnvironments = async (
  options: GetEnvironmentsOptions & ListOptions,
): Promise<void> => {
  const environments = await getEnvironments(options);

  if (options.json) {
    logJson(environments);
    return;
  }

  logger.info("Environments:");
  environments.forEach((environment) => {
    logger.info(`- Name: ${environment.name}`);
    logger.info(`  ID: ${environment.id}`);
    logger.info(`  Discovery URL: ${environment.discoveryUrl}`);
    logger.info(`  Updated At: ${environment.updatedAt}`);
  });
};

export const getEnvironments = async (
  options: GetEnvironmentsOptions,
): Promise<EnvironmentResponse[]> => {
  const { data, error } = await client.GET(
    "/apiKey/v3/test-targets/{testTargetId}/environments",
    {
      params: {
        path: { testTargetId: options.testTargetId },
      },
    },
  );

  handleError(error);

  if (!data) {
    throw new Error("no environments found");
  }

  return data;
};

export const createEnvironment = async (
  options: PostEnvironmentOptions & {
    testAccountUsername?: string;
    testAccountPassword?: string;
    basicAuthUsername?: string;
    basicAuthPassword?: string;
    privateLocationName?: string;
    testAccountOtpInitializerKey?: string;
  } & ListOptions,
): Promise<void> => {
  const { data, error } = await client.POST(
    "/apiKey/v3/test-targets/{testTargetId}/environments",
    {
      params: {
        path: { testTargetId: options.testTargetId },
      },
      body: {
        name: options.name,
        discoveryUrl: options.discoveryUrl,
        testAccount: {
          username: options.testAccountUsername,
          password: options.testAccountPassword,
        },
        basicAuth: {
          username: options.basicAuthUsername,
          password: options.basicAuthPassword,
        },
        testAccountOtpInitializerKey: options.testAccountOtpInitializerKey,
        privateLocationName: options.privateLocationName,
        additionalHeaderFields: options.additionalHeaderFields,
      },
    },
  );

  handleError(error);

  const response = data as EnvironmentResponse;

  if (options.json) {
    logJson(response);
    return;
  }

  logger.info("Environment created successfully!");
  logger.info(`- Name: ${response.name}`);
  logger.info(`  ID: ${response.id}`);
  logger.info(`  Discovery URL: ${response.discoveryUrl}`);
  logger.info(`  Updated At: ${response.updatedAt}`);
};

export const updateEnvironment = async (
  options: UpdateEnvironmentOptions &
    GetEnvironmentOptions & {
      testAccountUsername?: string;
      testAccountPassword?: string;
      basicAuthUsername?: string;
      basicAuthPassword?: string;
      privateLocationName?: string;
      testAccountOtpInitializerKey?: string;
    } & ListOptions,
): Promise<void> => {
  const { data, error } = await client.PATCH(
    "/apiKey/v3/test-targets/{testTargetId}/environments/{environmentId}",
    {
      params: {
        path: {
          testTargetId: options.testTargetId,
          environmentId: options.environmentId,
        },
      },
      body: {
        name: options.name,
        discoveryUrl: options.discoveryUrl,
        testAccount: {
          username: options.testAccountUsername,
          password: options.testAccountPassword,
        },
        otpInitializerKey: options.testAccountOtpInitializerKey,
        basicAuth: {
          username: options.basicAuthUsername,
          password: options.basicAuthPassword,
        },
        privateLocationName: options.privateLocationName,
      },
    },
  );

  handleError(error);

  const response = data as EnvironmentResponse;

  if (options.json) {
    logJson(response);
    return;
  }

  logger.info("Environment updated successfully!");
  logger.info(`- Name: ${response.name}`);
  logger.info(`  ID: ${response.id}`);
  logger.info(`  Discovery URL: ${response.discoveryUrl}`);
  logger.info(`  Updated At: ${response.updatedAt}`);
};

export const getEnvironment = async (
  options: GetEnvironmentOptions & ListOptions,
): Promise<void> => {
  const environments = await getEnvironments({
    testTargetId: options.testTargetId,
  });

  const environment = environments.find((e) => e.id === options.environmentId);
  if (!environment) {
    throw new Error("environment not found");
  }

  if (options.json) {
    logJson({ environment });
    return;
  }

  logger.info("Environment:");
  logger.info(`- Name: ${environment.name}`);
  logger.info(`  ID: ${environment.id}`);
  logger.info(`  Discovery URL: ${environment.discoveryUrl}`);
  logger.info(`  Updated At: ${environment.updatedAt}`);
};

export const deleteEnvironment = async (
  options: GetEnvironmentOptions & ListOptions,
): Promise<void> => {
  const { error } = await client.DELETE(
    "/apiKey/v3/test-targets/{testTargetId}/environments/{environmentId}",
    {
      params: {
        path: {
          testTargetId: options.testTargetId,
          environmentId: options.environmentId,
        },
      },
    },
  );

  handleError(error);

  if (options.json) {
    logJson({ success: true });
    return;
  }

  logger.info("Environment deleted successfully!");
};
