import type { paths, components } from "../api"; // generated by openapi-typescript
import { client, handleError, ListOptions, logJson } from "./client";
import { getUrl } from "../url";

export type GetNotificationsParams =
  paths["/apiKey/v2/test-targets/{testTargetId}/notifications"]["get"]["parameters"]["path"];
export type Notification = components["schemas"]["Notification"];

export const listNotifications = async (
  options: GetNotificationsParams & ListOptions,
): Promise<void> => {
  const { data, error } = await client.GET(
    "/apiKey/v2/test-targets/{testTargetId}/notifications",
    {
      params: {
        path: {
          testTargetId: options.testTargetId,
        },
      },
    },
  );

  handleError(error);
  const response = data as Notification[];
  if (options.json) {
    logJson(response);
    return;
  }

  console.log("Notifications:");
  for (const notification of response) {
    console.log(`\nID: ${notification.id}`);
    console.log(`Type: ${notification.type}`);
    console.log(`Created At: ${notification.createdAt}`);
    if (notification.payload?.testReportId) {
      console.log(`Test Report ID: ${notification.payload.testReportId}`);
      console.log(`URL: ${await getUrl({ testReportId: notification.payload.testReportId, entityType: "test-report" })}`);
    }
    if (notification.payload?.testCaseId) {
      console.log(`Test Case ID: ${notification.payload.testCaseId}`);
      console.log(`URL: ${await getUrl({ testCaseId: notification.payload.testCaseId, entityType: "test-case" })}`);
    }
    if (notification.payload?.failed !== undefined) {
      console.log(`Failed: ${notification.payload.failed}`);
    }
    if (notification.ack) {
      console.log(`Acknowledged: ${notification.ack}`);
    }
  }
};
