import type { components, paths } from "../api"; // generated by openapi-typescript
import { logger } from "../logger";
import { getUrl } from "../url";
import { client, handleError, ListOptions, logJson } from "./client";

export type GetNotificationsParams =
  paths["/apiKey/v3/test-targets/{testTargetId}/notifications"]["get"]["parameters"]["path"];
export type Notification = components["schemas"]["Notification"];

export const listNotifications = async (
  options: GetNotificationsParams & ListOptions,
): Promise<void> => {
  const { data, error } = await client.GET(
    "/apiKey/v3/test-targets/{testTargetId}/notifications",
    {
      params: {
        path: {
          testTargetId: options.testTargetId,
        },
      },
    },
  );

  handleError(error);
  const response = data as Notification[];
  if (options.json) {
    logJson(response);
    return;
  }

  logger.info("Notifications:");
  for (const notification of response) {
    logger.info(`\nID: ${notification.id}`);
    logger.info(`Type: ${notification.type}`);
    logger.info(`Created At: ${notification.createdAt}`);
    if (notification.payload?.testReportId) {
      logger.info(`Test Report ID: ${notification.payload.testReportId}`);
      logger.info(
        `URL: ${await getUrl({ testReportId: notification.payload.testReportId, entityType: "test-report" })}`,
      );
    }
    if (notification.payload?.testCaseId) {
      logger.info(`Test Case ID: ${notification.payload.testCaseId}`);
      logger.info(
        `URL: ${await getUrl({ testCaseId: notification.payload.testCaseId, entityType: "test-case" })}`,
      );
    }
    if (notification.payload?.failed !== undefined) {
      logger.info(`Failed: ${notification.payload.failed}`);
    }
    if (notification.ack) {
      logger.info(`Acknowledged: ${notification.ack}`);
    }
  }
};
