import type { components } from "../api"; // generated by openapi-typescript
import { logger } from "../logger";
import { client, handleError, ListOptions, logJson } from "./client";

export type SuccessResponse = components["schemas"]["SuccessResponse"];
export type PrivateLocationInfo = components["schemas"]["PrivateLocationInfo"];

export const registerLocation = async (
  options: {
    address: string;
    name: string;
    username: string;
    password: string;
  } & ListOptions,
): Promise<void> => {
  const { data, error } = await client.PUT(
    "/apiKey/v1/private-location/register",
    {
      body: {
        name: options.name,
        registrationData: {
          address: options.address,
          username: options.username,
          password: options.password,
        },
      },
    },
  );

  handleError(error);

  const response = data as SuccessResponse;

  if (options.json) {
    logJson(response);
    return;
  }

  logger.info(
    `Registration result: ${response.success ? "Success" : "Failed"}`,
  );
};

export const unregisterLocation = async (
  options: {
    name: string;
  } & ListOptions,
): Promise<void> => {
  const { data, error } = await client.PUT(
    "/apiKey/v1/private-location/unregister",
    {
      body: {
        name: options.name,
      },
    },
  );

  handleError(error);
  const response = data as SuccessResponse;

  if (options.json) {
    logJson(response);
    return;
  }

  logger.info(
    `Unregistration result: ${response.success ? "Success" : "Failed"}`,
  );
};

export const listPrivateLocations = async (
  options: ListOptions,
): Promise<void> => {
  const { data, error } = await client.GET("/apiKey/v1/private-location");

  handleError(error);

  const response = data as PrivateLocationInfo;
  if (options.json) {
    logJson(response);
    return;
  }

  logger.info("Private Locations:");
  response.forEach((location) => {
    logger.info(`- Name: ${location.name}`);
    logger.info(`  Status: ${location.status}`);
    logger.info(`  Address: ${location.address}`);
  });
};
