import type { components, paths } from "../api"; // generated by openapi-typescript
import { logger } from "../logger";
import { getUrl } from "../url";
import { client, handleError, ListOptions, logJson } from "./client";

export type ExecuteTestsBody =
  components["schemas"]["TestTargetExecutionRequest"];
export type GetTestReportParams =
  paths["/apiKey/v3/test-targets/{testTargetId}/test-reports/{testReportId}"]["get"]["parameters"]["path"];
export type TestReport = components["schemas"]["TestReport"];

export const executeTests = async (
  options: ExecuteTestsBody & { description?: string } & ListOptions,
): Promise<void> => {
  const { data, error } = await client.POST("/apiKey/v3/execute", {
    body: {
      testTargetId: options.testTargetId,
      url: options.url,
      context: {
        source: "manual",
        description: options.description || "CLI execution",
        triggeredBy: {
          type: "USER",
          userId: "cli-user",
        },
      },
      environmentName: options.environmentName,
      tags: options.tags,
      variablesToOverwrite: options.variablesToOverwrite,
      browser: options.browser,
      breakpoint: options.breakpoint,
    },
  });

  handleError(error);

  if (options.json) {
    logJson(data);
    return;
  }

  if (data) {
    logger.info("Test execution started successfully!");
    logger.info(`Test Report URL: ${data.testReportUrl}`);
    logger.info(`Report Status: ${data.testReport?.status}`);
    const numberOfTestResults = data.testReport?.testResults?.length ?? 0;
    if (numberOfTestResults > 0) {
      logger.info("\nTest Results:");
      data.testReport?.testResults?.forEach((result) => {
        logger.info(`- Test ${result.testCaseVersionId}: ${result.status}`);
        if (result.errorMessage) {
          logger.info(`  Error: ${result.errorMessage}`);
        }
        if (result.traceUrl) {
          logger.info(`  Trace: ${result.traceUrl}`);
        }
      });
    }
  }
};

export const getTestReports = async (options: {
  testTargetId: string;
}): Promise<TestReport[] | undefined> => {
  const { data, error } = await client.GET(
    "/apiKey/v3/test-targets/{testTargetId}/test-reports",
    {
      params: {
        path: {
          testTargetId: options.testTargetId,
        },
      },
    },
  );

  handleError(error);

  return data?.data;
};

export const listTestReport = async (
  options: GetTestReportParams & ListOptions,
): Promise<void> => {
  const { data, error } = await client.GET(
    "/apiKey/v3/test-targets/{testTargetId}/test-reports/{testReportId}",
    {
      params: {
        path: {
          testTargetId: options.testTargetId,
          testReportId: options.testReportId,
        },
      },
    },
  );

  handleError(error);

  if (options.json) {
    logJson(data);
    return;
  }

  const response = data as TestReport;
  logger.info("Test Report Details:");
  logger.info(`Status: ${response.status}`);
  logger.info(`Execution URL: ${response.executionUrl}`);
  const numberOfTestResults = response.testResults?.length ?? 0;
  if (numberOfTestResults > 0) {
    logger.info("\nTest Results:");
    for (const result of response.testResults ?? []) {
      logger.info(`- Test ${result.testCaseVersionId}: ${result.status}`);
      logger.info(
        `  ${await getUrl({
          testReportId: options.testReportId,
          testResultId: result.id ?? "",
          entityType: "test-result",
        })}`,
      );
      if (result.errorMessage) {
        logger.info(`  Error: ${result.errorMessage}`);
      }
      if (result.traceUrl) {
        logger.info(`  Trace: ${result.traceUrl}`);
      }
    }
  }
};
